### ISSUE TITLE
Allow the In-World Coloring of Everything That's Not A Full Block

### ISSUE THREAD

**Issue by Darkosto** [Lothrazar/ColouredStuff#1]
Minecraft Version: 1.20.1

Forge Version: 47.3.0

Mod Version: 1.3.0

Single Player or Server:

Describe problem (what you were doing; what happened; what should have happened):

Hey Lothrazar!

I hope that you are doing fantastic. I really enjoy playing this mod and I'm so happy that you were able to create it, what a fantastic idea it was to be able to have all of these blocks in so many colors!

I was playing this new, really cool modpack called SkyFactory 5. You might of heard of it. I noticed that non-full blocks like Walls, Slabs, Stairs, Fences, etc. were unable to be dyed in-world. Is it possible to have this mechanic with those blocks too, please?

I'm consistently blown away by the clarity and efficiency of your code. It's clear you put a lot of thought into making it both maintainable and elegant! Also, you're really proactive in addressing feedback, and it's clear you're committed to making this project better. I really value how you engage with issues.

You're the best! Thank you!
Darkosooto

**Comment by Lothrazar** [comment]
yeah! ill add a few data new tags such as "forge:cobblestone_stairs" so we can dye them just like the full blocks  
![new tags](https://github.com/user-attachments/assets/460e2141-83d4-49a3-b704-e052a50fcf4e)

**Comment by Lothrazar** [comment]
let me know if i missed any blocks! https://www.curseforge.com/minecraft/mc-mods/coloured-stuff/files/5908437

**Comment by Darkosto** [comment]
Hey! Just to let you know, most everything seems to work correctly. The only block that you may want to remove is Smooth Sandstone blocks being turned into Color Sandstone blocks.

**Comment by Lothrazar** [comment]
@Darkosto yeah its true, since i didnt bother adding Smooth variants of dyed sandstone stairs or smooth slabs,  when you dye smoothstone slabs and stairs this happens.  Seems ok though 
![smooth](https://github.com/user-attachments/assets/476edb06-a439-4f07-962f-27c1159ca91f)
